/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            screens: {
                // Width tiers (mobile-first)
                'xxs': '360px',
                'xs': '480px',
                'sm': '640px',
                'md': '768px',
                'tab': '820px',
                'lg': '1024px',
                'xl': '1280px',
                '2xl': '1536px',
                '3xl': '1920px',
                '4xl': '2560px',

                // Max-width precision helpers
                'max-xxs': { 'max': '359px' },
                'max-xs': { 'max': '479px' },
                'max-sm': { 'max': '639px' },
                'max-md': { 'max': '767px' },
                'max-tab': { 'max': '819px' },
                'max-lg': { 'max': '1023px' },
                'max-xl': { 'max': '1279px' },

                // Device/range helpers
                'phone': { 'min': '360px', 'max': '639px' },
                'phone-lg': { 'min': '480px', 'max': '767px' },
                'tablet': { 'min': '768px', 'max': '1023px' },
                'tablet-10': { 'min': '800px', 'max': '1280px' },
                'tablet-portrait': { 'raw': '(min-width: 768px) and (max-width: 1024px) and (orientation: portrait)' },
                'tablet-landscape': { 'raw': '(min-width: 1024px) and (max-width: 1366px) and (orientation: landscape)' },
                'laptop': { 'min': '1024px', 'max': '1439px' },
                'desktop': { 'min': '1440px', 'max': '1919px' },
                'ultrawide': { 'min': '1920px' },

                // Height-aware helpers
                'h-short': { 'raw': '(max-height: 699px)' },
                'h-medium': { 'raw': '(min-height: 700px) and (max-height: 899px)' },
                'h-tall': { 'raw': '(min-height: 900px)' },
                'h-xl': { 'raw': '(min-height: 1080px)' },
            },
            colors: {
                primary: {
                    50: '#EAFAFF',
                    100: '#14ABD5',
                    200: '#075EA6',
                    300: '#1C3F78',
                },
                neutral: {
                    50: '#FFFFFF',
                    200: '#E6E6E6',
                    300: '#BFBFBF',
                    400: '#8C8C8C',
                    500: '#3D3D3D',
                    600: '#000000',
                },
                warning: {
                    100: '#FFC107',
                }
            },
            backgroundImage: {
                'gradient-brand': 'linear-gradient(276.97deg, #1C3F78 0.33%, #14ABD5 99.67%)',
                'gradient-teal': 'linear-gradient(270deg, rgba(20, 171, 213, 0) 31.83%, #14ABD5 97.67%)',
                'gradient-sky': 'linear-gradient(266.84deg, rgba(234, 250, 255, 0) 14.24%, #EAFAFF 89.25%)',
                'gradient-blue': 'linear-gradient(267.95deg, rgba(7, 94, 166, 0) 24.1%, #075EA6 91.85%)',
            },
            fontFamily: {
                display: ['"Funnel Display"', 'sans-serif'],
                sans: ['"Funnel Display"', 'sans-serif'],
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('@tailwindcss/forms'),
    ],
    // Safelist dynamic classes generated by PHP (GalleryController aspect ratios)
    safelist: [
        'aspect-[3/4]',
        'aspect-[4/3]',
        'aspect-square',
        'aspect-[2/3]',
        'aspect-[16/9]',
    ],
};
